package POJOs;
// Generated 25-ene-2019 9:10:28 by Hibernate Tools 3.6.0

import java.util.Set;




/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int numDepartamento;
     private String nomeDepartamento;
//     9B1
     private Empregado empregado; //director
//     9C1
     private Set<Proxecto> proxectos;

    public Departamento() {
    }

    public Departamento(int numDepartamento, String nomeDepartamento) {
       this.numDepartamento = numDepartamento;
       this.nomeDepartamento = nomeDepartamento;
    }
   
    public int getNumDepartamento() {
        return this.numDepartamento;
    }
    
    public void setNumDepartamento(int numDepartamento) {
        this.numDepartamento = numDepartamento;
    }
    public String getNomeDepartamento() {
        return this.nomeDepartamento;
    }
    
    public void setNomeDepartamento(String nomeDepartamento) {
        this.nomeDepartamento = nomeDepartamento;
    }

    public Empregado getEmpregado() {
        return empregado;
    }

    public void setEmpregado(Empregado empregado) {
        this.empregado = empregado;
    }
//    9C1
    public Set<Proxecto> getProxectos() {
        return proxectos;
    }

    public void setProxectos(Set<Proxecto> proxectos) {
        this.proxectos = proxectos;
    }

    @Override
    public String toString() {
        return "Departamento" + "numDepartamento= " + numDepartamento + ", nomeDepartamento= " + nomeDepartamento + ", director= " + empregado + ", numProxectos= " + proxectos.size();
    }
    
}


