package POJOs;
// Generated 25-ene-2019 9:10:28 by Hibernate Tools 3.6.0


import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.hibernate.mapping.Bag;

/**
 * Empregado generated by hbm2java
 */
public class Empregado  implements java.io.Serializable {


     private String nss;
     private String nome;
     private String apelido1;
     private String apelido2;
     private Date dataNacemento;
////     comentado para facer o exercicio 10
//     private Double salario;
     private char sexo;
////       7A2
//     private Set<String> telefonos;
////     7A7
//     private Set<Telefono> telefonos;
////     7B1
//     // HashMap DIFERENTE de Map
//     private Map<String, String> telefonos;
////     7C1
//     private Collection<Telefono> telefonos;
////     7D1
//     private List<Telefono> telefonos;  
////     7E1
//     private Collection<HoraExtra> horas;
//     9A1
     private Vehiculo vehiculo;
////     9D1
//     private Collection<Proxecto> proxectos = new ArrayList<Proxecto>();
//     9D4
     private Set<EmpregadoProxecto> proxectos = new HashSet<EmpregadoProxecto>();
     
    public Empregado() {
    }
	
    public Empregado(String nss, String nome, String apelido1, char sexo) {
        this.nss = nss;
        this.nome = nome;
        this.apelido1 = apelido1;
        this.sexo = sexo;
    }
    public Empregado(String nss, String nome, String apelido1, String apelido2, Date dataNacemento, Double salario, char sexo) {
       this.nss = nss;
       this.nome = nome;
       this.apelido1 = apelido1;
       this.apelido2 = apelido2;
       this.dataNacemento = dataNacemento;
//       comentado para facer o exercicio 10
//       this.salario = salario;
       this.sexo = sexo;
////       7B1
//       telefonos = new HashMap<String, String>();
//       
////       7C1
//       telefonos = new ArrayList<Telefono>();
//       
////       7D1
//        telefonos = new ArrayList<Telefono>();
    }
   
    public String getNss() {
        return this.nss;
    }
    
    public void setNss(String nss) {
        this.nss = nss;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getApelido1() {
        return this.apelido1;
    }
    
    public void setApelido1(String apelido1) {
        this.apelido1 = apelido1;
    }
    public String getApelido2() {
        return this.apelido2;
    }
    
    public void setApelido2(String apelido2) {
        this.apelido2 = apelido2;
    }
    public Date getDataNacemento() {
        return this.dataNacemento;
    }
    
    public void setDataNacemento(Date dataNacemento) {
        this.dataNacemento = dataNacemento;
    }
    
//    comentado para facer o exercicio 10
//    public Double getSalario() {
//        return this.salario;
//    }
//    
//    public void setSalario(Double salario) {
//        this.salario = salario;
//    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }

////    7A6
//    public void setTelefonos(Set<String> telefonos) {
//        this.telefonos = telefonos;
//    }
//
//    public Set<String> getTelefonos() {
//        return telefonos;
//    }
////      7A7
//    public void setTelefonos(Set<Telefono> telefonos) {
//        this.telefonos = telefonos;
//    }
//
//    public Set<Telefono> getTelefonos() {
//        return telefonos;
//    }
//    
////    7B1
//    public Map<String, String> getTelefonos() {
//        return telefonos;
//    }
//
//    public void setTelefonos(Map<String, String> telefonos) {
//        this.telefonos = telefonos;
//    }
//    
////    7C1
//    public Collection<Telefono> getTelefonos() {
//        return telefonos;
//    }
//
//    public void setTelefonos(Collection<Telefono> telefonos) {
//        this.telefonos = telefonos;
//    }
//
////    7D1
//    public void setTelefonos(List<Telefono> telefonos) {
//        this.telefonos = telefonos;
//    }
//
//    public List<Telefono> getTelefonos() {
//        return telefonos;
//    }
//    
////    7E1
//        public Collection<HoraExtra> getHoras() {
//        return horas;
//    }
//
//    public void setHoras(Collection<HoraExtra> horas) {
//        this.horas = horas;
//    }
//    
//    9A1
    public Vehiculo getVehiculo() {
        return vehiculo;
    }

    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }

////    9D1
//    public Collection<Proxecto> getProxectos() {
//        return proxectos;
//    }
//
//    public void setProxectos(Collection<Proxecto> proxectos) {
//        this.proxectos = proxectos;
//    }
//    
//    9D4
    public Set<EmpregadoProxecto> getProxectos() {
        return proxectos;
    }

    public void setProxectos(Set<EmpregadoProxecto> empregadoProxecto) {
        this.proxectos = empregadoProxecto;
    }

    @Override
    public String toString() {
        return "nss= " + nss + ", nome=" + nome + ", apelido1=" + apelido1 + ", apelido2=" + apelido2 + ", dataNacemento=" + dataNacemento + ", sexo=" + sexo;
    }
}


