package POJOs;
// Generated 25-ene-2019 9:10:28 by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;




/**
 * Proxecto generated by hbm2java
 */
public class Proxecto  implements java.io.Serializable {


     private int numProxecto;
     private String nomeProxecto;
     private String lugar;
//     9C1
     private Departamento departamento;
//     9D1
     private Collection<EmpregadoProxecto> empregados = new ArrayList<EmpregadoProxecto>();

    public Proxecto() {
    }

	
    public Proxecto(int numProxecto, String nomeProxecto) {
        this.numProxecto = numProxecto;
        this.nomeProxecto = nomeProxecto;
    }
    public Proxecto(int numProxecto, String nomeProxecto, String lugar) {
       this.numProxecto = numProxecto;
       this.nomeProxecto = nomeProxecto;
       this.lugar = lugar;
    }
   
    public int getNumProxecto() {
        return this.numProxecto;
    }
    
    public void setNumProxecto(int numProxecto) {
        this.numProxecto = numProxecto;
    }
    public String getNomeProxecto() {
        return this.nomeProxecto;
    }
    
    public void setNomeProxecto(String nomeProxecto) {
        this.nomeProxecto = nomeProxecto;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
//  9C1
    public Departamento getDepartamento() {
        return departamento;
    }

    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
//  9D1
    public Collection getEmpregados() {
        return empregados;
    }

    public void setEmpregados(Collection empregados) {
        this.empregados = empregados;
    }

    @Override
    public String toString() {
        return "Proxecto " + "numProxecto= " + numProxecto + ", nomeProxecto= " + nomeProxecto + ", lugar= " + lugar + ", departamento= " + departamento;
    }
}


